import BDL.Core.Satisfaction

/-!
# Env — global well-formedness and the Phase-1 preservation theorems

The Phase-1 research question:

> Can `B` be progressively refined or later realized without editing `A`,
> while preserving the typing and previous commitments of `A`?

Answered in two halves, under deliberately different hypotheses:

* **Typing** (`local_refinement_preserves_global_typing`): needs only the
  *structural* step `DeclLeq B B'` — no evidence, no well-formedness, no
  monotonicity.  Strictly, it needs even less: only that `B'` keeps `B`'s
  expected type (`HasType.mono_env`).
* **Commitments** (`local_refinement_preserves_global_wf`): needs the step's
  side conditions *and* `Evidence.Monotone`.  The monotonicity requirement is
  not decorative — `Experiments.nonmonotone_evidence_breaks_preservation`
  shows the theorem is false without it.

Both are consequences of one structural fact: the environment order
`EnvRefines` is generated by `update` at a preserved id (`EnvRefines_update`).
-/

namespace BDL

/-- Every declaration is stored under its own id, and its realization (if
    any) satisfies its interface *in this environment*, at top level. -/
def GlobalWF (ev : Evidence) (Θ : ConceptEnv) (Δ : DeclEnv) : Prop :=
  ∀ id h, Δ id = some h → h.id = id ∧ WellFormedDecl ev Θ Δ [] h

theorem GlobalWF.empty (ev : Evidence) (Θ : ConceptEnv) : GlobalWF ev Θ .empty :=
  fun _ _ h => nomatch h

/-- For finite environments, global well-formedness reduces to a decidable
    check over the list. -/
theorem GlobalWF.ofList {ev : Evidence} {Θ : ConceptEnv} {l : List DesignDecl}
    (h : ∀ dh ∈ l, WellFormedDecl ev Θ (.ofList l) [] dh) : GlobalWF ev Θ (.ofList l) := by
  intro id dh hh
  obtain ⟨hmem, dId⟩ := DeclEnv.ofList_some hh
  exact ⟨dId, h dh hmem⟩

theorem GlobalWF.stored_id {ev : Evidence} {Θ : ConceptEnv} {Δ : DeclEnv} (g : GlobalWF ev Θ Δ) {id : DeclId} {h : DesignDecl}
    (hh : Δ id = some h) : h.id = id := (g id h hh).1

theorem GlobalWF.wellFormed {ev : Evidence} {Θ : ConceptEnv} {Δ : DeclEnv} (g : GlobalWF ev Θ Δ) {id : DeclId} {h : DesignDecl}
    (hh : Δ id = some h) : WellFormedDecl ev Θ Δ [] h := (g id h hh).2

/-- **Binding a representation preserves global well-formedness** (Phase 3):
    the concept environment is write-once and typing is monotone in it. -/
theorem GlobalWF.of_conceptRefines {ev : Evidence} {Θ₁ Θ₂ : ConceptEnv} (hc : ConceptRefines Θ₁ Θ₂)
    {Δ : DeclEnv} (g : GlobalWF ev Θ₁ Δ) : GlobalWF ev Θ₂ Δ :=
  fun _ _ hh => ⟨g.stored_id hh, (g.wellFormed hh).of_conceptRefines hc⟩

/-! ## Phase-1 main theorems -/

/-- **Local refinement preserves global typing.**

Stepping the declaration `B` to any structurally later state `B'` and
writing it back preserves *every* typing judgment in the design — every
client of `B`, and every non-client, unchanged.

Hypotheses: `B` is declared, and `DeclLeq B B'`.  Nothing about evidence,
commitments being satisfied, or well-formedness of anything.  In fact only
`B'.interface.expectedType = B.interface.expectedType` is used (via `EnvRefines.tyView`). -/
theorem local_refinement_preserves_global_typing {Θ : ConceptEnv} {G : Grant} {Δ : DeclEnv} {B B' : DesignDecl}
    (hB : Δ B.id = some B) (le : DeclLeq B B') :
    ∀ {Γ : Ctx} {e : Expr} {τ : Ty}, HasType Θ Δ G Γ e τ → HasType Θ (Δ.update B') G Γ e τ :=
  fun h => h.of_envRefines (EnvRefines_update hB le)

/-- **Local refinement preserves global well-formedness.**

If the design is globally well formed and `B` takes one lifecycle step
(side conditions checked in the current environment), the updated design is
globally well formed — provided evidence is monotone. -/
theorem local_refinement_preserves_global_wf {ev : Evidence} (mono : ev.Monotone) {Θ : ConceptEnv}
    {Δ : DeclEnv} (g : GlobalWF ev Θ Δ) {B B' : DesignDecl}
    (hB : Δ B.id = some B) (step : DeclRefines ev Θ Δ [] B B') :
    GlobalWF ev Θ (Δ.update B') := by
  have er : EnvRefines Δ (Δ.update B') := EnvRefines_update hB step.toLeq
  intro id h hh
  by_cases dId : id = B'.id
  · subst dId
    rw [Δ.update_self] at hh
    cases hh
    exact ⟨rfl, step.wellFormed_target.of_envRefines mono er⟩
  · rw [Δ.update_other B' dId] at hh
    exact ⟨g.stored_id hh, (g.wellFormed hh).of_envRefines mono er⟩

/-- Updating twice at the same id is updating once (needs `funext`). -/
theorem DeclEnv.update_update_same {Δ : DeclEnv} {h₁ h₂ : DesignDecl} (dId : h₁.id = h₂.id) :
    (Δ.update h₁).update h₂ = Δ.update h₂ := by
  funext id
  unfold DeclEnv.update
  by_cases h : id = h₂.id <;> simp [h, dId]

/-- Multi-step version: a whole lifecycle of `B`, all side conditions checked
    against the *original* environment, preserves global well-formedness. -/
theorem local_lifecycle_preserves_global_wf {ev : Evidence} (mono : ev.Monotone) {Θ : ConceptEnv}
    {Δ : DeclEnv} (g : GlobalWF ev Θ Δ) {B B' : DesignDecl}
    (hB : Δ B.id = some B) (steps : DeclRefinesStar ev Θ Δ [] B B') :
    GlobalWF ev Θ (Δ.update B') := by
  -- generalize over the environment the steps are replayed in
  suffices key : ∀ Δ', EnvRefines Δ Δ' → GlobalWF ev Θ Δ' → Δ' B.id = some B →
      GlobalWF ev Θ (Δ'.update B') from
    key Δ (EnvRefines.refl Δ) g hB
  clear hB g
  induction steps with
  | refl B =>
    intro Δ' _ g' hB' id h hh
    have er' : EnvRefines Δ' (Δ'.update B) := EnvRefines_update hB' (DeclLeq.refl _)
    by_cases dId : id = B.id
    · subst dId; rw [Δ'.update_self] at hh; cases hh
      exact ⟨rfl, (g'.wellFormed hB').of_envRefines mono er'⟩
    · rw [Δ'.update_other B dId] at hh
      exact ⟨g'.stored_id hh, (g'.wellFormed hh).of_envRefines mono er'⟩
  | step s rest ih =>
    rename_i B B₁ B'
    intro Δ' er g' hB'
    have s' : DeclRefines ev Θ Δ' [] B B₁ := s.of_envRefines mono er
    have g₁ := local_refinement_preserves_global_wf mono g' hB' s'
    have er₁ : EnvRefines Δ (Δ'.update B₁) := er.trans (EnvRefines_update hB' s.toLeq)
    have hB₁ : (Δ'.update B₁) B₁.id = some B₁ := Δ'.update_self B₁
    have := ih (Δ'.update B₁) er₁ g₁ hB₁
    rwa [DeclEnv.update_update_same (DeclRefinesStar.toLeq rest).id_eq] at this

end BDL
